CREATE USER gpad PASSWORD 'gpad';
CREATE DATABASE gpad WITH ENCODING='UTF8' OWNER=gpad;
GRANT ALL PRIVILEGES ON DATABASE gpad TO gpad;
GRANT ALL PRIVILEGES ON SCHEMA public TO gpad;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO gpad;