version: '3.5'

services:

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dbinit.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - gpad-app

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - gpad-app

networks:
    gpad-app:
        name: gpad-app

volumes:
  postgres_data: