version: '3.5'

services:
  db:
    # port 5432
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./entrypoint.d:/docker-entrypoint-initdb.d
    networks:
      - gpad-app

  adminer:
    # port 8080
    image: adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - gpad-app

  caddy:
    build: ./caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - gpad-app

  blue-two:
    build: git@github.com:underscoredotspace/blue-two.git#manual_npsso
    depends_on:
      - db
    restart: unless-stopped
    environment:
      NODE_ENV: "production"
      POSTGRES: $POSTGRES
    ports:
      - 3002:3002
    networks:
      - gpad-app  

  claude: 
    build: git@github.com:underscoredotspace/claude-v2.git#use-discordjs-slash
    restart: unless-stopped
    depends_on:
      - db
      - gpad-api
    environment:
        NODE_ENV: "production"
        POSTGRES: $POSTGRES
        DISCORD_APPID: $DISCORD_APPID
        DISCORD_TOKEN: $DISCORD_TOKEN
        CLAUDE_LOG: $CLAUDE_LOG
        GUILD: $GUILD
    networks:
      - gpad-app

  gpad-api:
      build: git@github.com:underscoredotspace/discord-api#main
      depends_on:
        - db
      restart: unless-stopped
      environment:
          NODE_ENV: "production"
          POSTGRES: $POSTGRES
          DISCORD_TOKEN: $DISCORD_TOKEN
          GUILD_ID: $GUILD
          DISCORD_CLIENT_ID: $DISCORD_CLIENT_ID
          DISCORD_CLIENT_SECRET: $DISCORD_CLIENT_SECRET
          DISCORD_CALLBACK: $DISCORD_CALLBACK
          DISCORD_AUTH_SCOPE: $DISCORD_AUTH_SCOPE
          LOGIN_REDIRECT_URL: $LOGIN_REDIRECT_URL
          COOKIE_DOMAIN: $COOKIE_DOMAIN
          COOKIE_NAME: $COOKIE_NAME
          COOKIE_SECRET: $COOKIE_SECRET
          CORS: $CORS
          SUPER_USER: $SUPER_USER
          WEB_ADMIN: $WEB_ADMIN
      ports:
          - 3001:3001
      networks:
          - gpad-app

networks:
    gpad-app:
        name: gpad-app

volumes:
  postgres_data:
  caddy_data:
    external: true
  caddy_config: 